### ISSUE TITLE
VSCode ext: Custom tasks prefixed with `.:` instead of `ccd:` or `concordium:`

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-smart-contract-tools#63]
**Bug Description**

The configurable tasks are prefixed with `.:` instead of `ccd:` or `concordium:`.
In comparison, the regular rust tasks are prefixed with `rust:`.
I assume that this can lead to confusion, if you also have tasks for smart contracts on other chains. For example for the build task, which has the full name `.: Build smart contract`

**Steps to Reproduce**
1. Run `Tasks: Configure Task`
2. See the names of the different tasks available

**Expected Result**
`rust: cargo clean`
...
`concordium: Build smart contract`
`concordium: Test smart contract`

**Actual Result**
`rust: cargo clean`
...
`.: Build smart contract`
`.: Test smart contract`

**Versions**
- Software Version: 0.1.0-0
- OS: macOS Ventura (Apple M2)

**Comment by limemloh** [comment]
Right, will fix this.

Just for information, it only happens when the smart contract project root is opened in VS Code, as the `.` is currently representing the relative path where the task originated from.
So when opening a directory with multiple smart contracts, this becomes the path to each of them, so they can be distinguished.
